"""RL algorithm implementations."""

from helios.algorithms.tdmpc2 import (
    Encoder,
    Dynamics,
    RewardHead,
    QEnsemble,
    Pi,
    sample_pi,
    MultiEnvBuffer,
    make_update_fn as tdmpc2_make_update_fn,
    make_mppi_fn,
    simnorm,
    symlog,
    symexp,
    two_hot,
    two_hot_inv,
    soft_ce,
    DEFAULTS as TDMPC2_DEFAULTS,
)
from helios.algorithms.tdmpc_glass import (
    init_glass_params,
    glass_transition_graph,
    glass_loss_and_aux,
    make_glass_diag_fn,
    make_update_fn as tdmpc_glass_make_update_fn,
    DEFAULTS as TDMPC_GLASS_DEFAULTS,
)
from helios.algorithms.ppo import (
    PolicyNet,
    ValueNet,
    tanh_normal_logprob as ppo_tanh_normal_logprob,
    tanh_normal_entropy,
    ObsNormState,
    obs_norm_init,
    obs_norm_update,
    obs_norm_apply,
    Storage as PPOStorage,
    compute_gae_mb,
    ppo_loss_fn,
    make_update_fn as ppo_make_update_fn,
    DEFAULTS as PPO_DEFAULTS,
)
from helios.algorithms.sac import (
    MLP,
    Actor,
    TwinCritic,
    tanh_normal_sample,
    tanh_normal_log_prob as sac_tanh_normal_log_prob,
    make_sac_fns,
    make_scan_update,
    make_collect_fn,
    evaluate as sac_evaluate,
    DEFAULTS as SAC_DEFAULTS,
)

__all__ = [
    # TD-MPC2
    "Encoder",
    "Dynamics",
    "RewardHead",
    "QEnsemble",
    "Pi",
    "sample_pi",
    "MultiEnvBuffer",
    "tdmpc2_make_update_fn",
    "make_mppi_fn",
    "simnorm",
    "symlog",
    "symexp",
    "two_hot",
    "two_hot_inv",
    "soft_ce",
    "TDMPC2_DEFAULTS",
    # TD-MPC-Glass
    "init_glass_params",
    "glass_transition_graph",
    "glass_loss_and_aux",
    "make_glass_diag_fn",
    "tdmpc_glass_make_update_fn",
    "TDMPC_GLASS_DEFAULTS",
    # PPO (v34s3 milestone)
    "PolicyNet",
    "ValueNet",
    "ppo_tanh_normal_logprob",
    "tanh_normal_entropy",
    "ObsNormState",
    "obs_norm_init",
    "obs_norm_update",
    "obs_norm_apply",
    "PPOStorage",
    "compute_gae_mb",
    "ppo_loss_fn",
    "ppo_make_update_fn",
    "PPO_DEFAULTS",
    # SAC (custom v1 milestone)
    "MLP",
    "Actor",
    "TwinCritic",
    "tanh_normal_sample",
    "sac_tanh_normal_log_prob",
    "make_sac_fns",
    "make_scan_update",
    "make_collect_fn",
    "sac_evaluate",
    "SAC_DEFAULTS",
]
